#define PI 3.1415926


extern int Fahrenheit_convert_Celsius(int f);
extern void cul_circle_ball(float r, float h);
extern int add(float a, float b);
extern void show1();
extern int cul_average(float a, float b, float c);
extern void int_cul(int num1, int num2);
extern double cul_mortality_rate(int num1, int num2);
extern int cul_digit_sum(int num);
extern int cul_area(float r, int n);
extern void cul_equation(double a, double b, double c);
extern double cul_abs(double a);
extern int exchange(int num);
extern double cul_distence(double x1, double y1, double x2, double y2);
extern void print8d(int a, int b, int c);
extern void ASDQ();
extern int cul_profit(int a);
extern void poker(char hua, int num);
extern void judge_Aa1other(char ch);
extern void culculate();
extern void num_conversion(int x);
extern int isDivisible(int a, int b);
extern void judge_in(int x, int y);
extern int jud1 (double a,double b,double c);
extern int jud2 (double a,double b,double c);
extern void judge_triangle(double a, double b, double c);
extern void cul1(double x, double y, int a);
extern int judge135(int a);
extern void div_with_remain(int a, int b);
extern void pay(int yuan);
extern void cul_time();
extern int jud (int x);
extern int flower(int start, int end);
extern void cul_Hex();
extern void jud_return();
extern int fact_(int n);
extern int numa(int a,int i);
extern int a_aa_aaa(int a, int n);
extern void show();
extern int cul2(double x);
extern int monkey(int n);
extern long long N123sum(int n);
extern void cul_count();
extern void print (int x);
extern int find();
extern int common_num(int a, int b);
extern int problem_3_add_1(int n);
extern void ball_fall(float m, int n);
extern double sum1_a(int a, int b, int c);
extern int a_k_pow_sum(int n, int k);
extern void power_alph();
extern void jud_perfect_number();
extern int prime_sum();
extern int judge_crash(double x1,double y1,double x2,double y2,double x3,double y3,double x4,double y4);
extern int diamond_praise(int n, int m, double x, double y, double r);
extern void pyramid(int num, char ch);
extern int jud3(int n);
extern int jud4(int n);
extern int symmetry_prime(int num);
extern void figure(int n);
extern void string_statistics();
extern void choose();
extern void arr_divisible(int num [20]);
extern double dog_belly(int n, char trc, int a, int b);
extern int nagetive_number_count(int num[10]);
extern void arr_common(int a[6], int b[8]);
extern void array_add(int a[15][15], int b[15][15], int n, int m);
extern void bubble_sort(int num[], int n);
extern void choose_sort();
extern void odd_even_sort();
extern void arr_statistics();
extern void arr_delete();
extern void common_item();
extern void Magic_square_matrix();
extern void insert_in_array(int num[10]);
extern void Joseph_ring(int n);
extern void dig_26_num(int N);
extern void Matrix_rotation();
extern int check1(int a[500][500], int i, int j, int n);
extern void Saddle_point();
extern int Max(int a[10][10], int n, int j);
extern int Sum(int a[10][10], int n, int j);
extern void Matrix_max_sum();
extern void change_string();
extern void IDcard();
extern void add(char a[], char b[], char c[]);
extern void long_long_long();
extern void apple_ming();
extern void Minesweeping();
extern float fact(int n);
extern int Cmn(int m, int n);
extern int isprime(int n);
extern int m_n_prime_sum(int m, int n);
extern int check3(point a);
extern void in_or_out();

