server:
  port: 8989
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kritsblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: fun.krits.entity